name = "malkolm-website"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./"
binding = "ASSETS"

[[kv_namespaces]]
binding = "WAITLIST"
id = "5fa2eda65a8a4983ae154cc2b77c38d6"
